#!/bin/bash

set -e

DIST=dist

case "$1" in
    chrome)
        mkdir -p $DIST/chrome
        cp -r src/common/* $DIST/chrome/
        cp -r src/chrome $DIST/
        ;;
    firefox)
        rm -fR $DIST/firefox
        mkdir -p $DIST/firefox/data

        cp -r src/common/* $DIST/firefox/data/
        cp -r src/firefox $DIST/

		# create lib/main.js containing data/js/{util,browser_base,browser,main}.js
		# This avoids the use of require() as well as the duplicate files in
		# lib/ and data/
		#
        cat $DIST/firefox/data/js/{util,browser_base,browser,main}.js > $DIST/firefox/lib/main.js
        rm $DIST/firefox/data/js/main.js	# not needed, avoid duplicates
	cd ./dist/firefox
	jpm xpi
	mv location-spoofer.xpi ./../../
        ;;
    clean)
        rm -rf $DIST
        ;;
    *)
        echo use deploy {chrome,firefox,clean}
esac
